# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          # Lines
          plugin_lines: yes
          # Traffic
          plugin_traffic: yes
          # Habits
          plugin_habits: yes
          plugin_habits_from: 500
          plugin_habits_charts: yes
          config_timezone: UTC
          # Followup
          plugin_followup: yes
          # Topics
          #plugin_topics: yes
          #plugin_topics_sort: stars
          #plugin_topics_mode: mastered
          #plugin_topics_limit: 0
          # Languages
          plugin_languages: yes
          plugin_languages_ignored: html, css, shell
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%
          plugin_languages_limit: 8
          # Iso Calendar
          plugin_isocalendar: yes
